create database customer_behaviour;

select * from customer limit 20;
# analysis

# what is the total revenue generated by male vs female customer
select gender, sum(purchase_amount) as revenue
from customer
group by gender;

#which customer used a dicount but still spent more than the average purchase amount
select customer_id, purchase_amount
from customer
where discount_applied = 'yes' and purchase_amount >= (select avg(purchase_amount) from customer);

#which are the top 5 products with the highest average review rating
select Item_Purchased, round(avg(review_rating),2) as average_review_rating
from customer
group by Item_Purchased
order by average_review_rating
limit 5;

#compare the average purchase amounts between Standard and express shipping
select Shipping_Type, round(avg(Purchase_Amount),2) as average_Purchase_Amount
from customer
where Shipping_Type in ('Standard','Express')
group by Shipping_Type;

# Do subcribed customer spend more? compare average spend and total revenue
# between revenue between subcribers and non-subcribers.
select Subscription_Status, 
count(customer_id) as total_customer,
round(avg(Purchase_Amount),2) as avg_spend,
sum(Purchase_Amount) as total_revenue
from customer
group by  Subscription_Status
order by avg_spend, total_revenue desc;

# which 5 product have the higest percentage of purcahse with discount applied
select item_Purchased,
round(sum(case when discount_applied = 'yes' then 1 else 0 end) / count(*) *100,2) as discount_rate
from customer
group by item_Purchased
order by discount_rate DESC
limit 5;

#segement customer into new, returning, loyal based on 
#their total number of pervious purchases and show the count of each segment
with customer_types as (
select customer_id, previous_purchases,
case when previous_purchases = 1 then 'New'
when previous_purchases between 2 and 10 then 'returning'
else 'loyal' end as customer_segment
from customer
)
select customer_segment, count(*) as number_of_customer
from customer_types
group by customer_segment;

#What are the top 3 most purchase product within each category?
with items_count as (
select category, item_purchased,
count(customer_id) as total_orders,
row_number() over (partition by category order by count(customer_id) desc) as item_rank
from customer
group by category, item_purchased
)
select category, item_purchased, total_orders, item_rank
from  items_count
where item_rank <=3;

# are customers who are repeat buyers (more than 5 pervious purchases) also likely to subscribes?
select subscription_status, count(customer_id) as repeat_buyers
from customer
where previous_purchases >5
group by subscription_status;

# what is the  revenue contribution of each age group?
select age_group , sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;




